### ISSUE TITLE
Error with vcf file

### ISSUE THREAD

**Issue by XMTian** [pievos101/PopGenome#12]
Dear Bastian,

When I read in a vcf file, I encountered this error, could you please help to tell me how to solve it?

VCF_readIntoCodeMatrix :: Malformed GT field!
Error in 1:numusedcols : NA/NaN argument
Calls: readVCF

Thank you so much for your attention and participation.

Best wishes,
Xiaomeng

**Comment by drew-olson-tmru** [comment]
Hi @XMTian how did you solve this? I am running into the same issue and not sure why.
